# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [1]:
# Please consult the lectures

In [3]:
import pandas as pd

# Sample DataFrame as per the provided data
data = {
    "Car Model": ["BMW X5", "BMW X5", "BMW X5", "BMW X5", "BMW X5", 
                  "Audi A5", "Audi A5", "Audi A5", "Audi A5", 
                  "Mercedez Benz C class", "Mercedez Benz C class", 
                  "Mercedez Benz C class", "Mercedez Benz C class"],
    "Mileage": [69000, 35000, 57000, 22500, 46000, 
                59000, 52000, 72000, 91000, 
                67000, 83000, 79000, 59000],
    "Sell Price($)": [18000, 34000, 26100, 40000, 31500, 
                      29400, 32000, 19300, 12000, 
                      30000, 40000, 21000, 33000],
    "Age(yrs)": [6, 3, 5, 2, 4, 
                 5, 4, 3, 8, 
                 6, 7, 7, 5]
}



In [9]:
df = pd.DataFrame(data)
df


Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         4
7                 Audi A5    72000          19300         3
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          30000         6
10  Mercedez Benz C class    83000          40000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [13]:
# Perform one-hot encoding
df_encoded = pd.get_dummies(df, columns=["Car Model"])

# Display the resulting DataFrame
df_encoded

Mileage  Sell Price($)  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5  \
0     69000          18000         6              False              True   
1     35000          34000         3              False              True   
2     57000          26100         5              False              True   
3     22500          40000         2              False              True   
4     46000          31500         4              False              True   
5     59000          29400         5               True             False   
6     52000          32000         4               True             False   
7     72000          19300         3               True             False   
8     91000          12000         8               True             False   
9     67000          30000         6              False             False   
10    83000          40000         7              False             False   
11    79000          21000         7              False             False   
12    59000          33000         5              False             False   

    Car Model_Mercedez Benz C class  
0                             False  
1                             False  
2                             False  
3                             False  
4                             False  
5                             False  
6                             False  
7                             False  
8                             False  
9                              True  
10                             True  
11                             True  
12                             True

In [15]:
import pandas as pd 

Df = {
    "Car Model": ["BMW X5", "BMW X5", "BMW X5", "BMW X5", "BMW X5", 
                  "Audi A5", "Audi A5", "Audi A5", "Audi A5", 
                  "Mercedez Benz C class", "Mercedez Benz C class", 
                  "Mercedez Benz C class", "Mercedez Benz C class"],
    "Mileage": [69000, 35000, 57000, 22500, 46000, 
                59000, 52000, 72000, 91000, 
                67000, 83000, 79000, 59000],
    "Sell Price($)": [18000, 34000, 26100, 40000, 31500, 
                      29400, 32000, 19300, 12000, 
                      30000, 40000, 21000, 33000],
    "Age(yrs)": [6, 3, 5, 2, 4, 
                 5, 4, 3, 8, 
                 6, 7, 7, 5]
}

df = pd.DataFrame(Df)

df_encoded = pd.get_dummies(df, columns=["Car Model"])
df_encoded

Mileage  Sell Price($)  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5  \
0     69000          18000         6              False              True   
1     35000          34000         3              False              True   
2     57000          26100         5              False              True   
3     22500          40000         2              False              True   
4     46000          31500         4              False              True   
5     59000          29400         5               True             False   
6     52000          32000         4               True             False   
7     72000          19300         3               True             False   
8     91000          12000         8               True             False   
9     67000          30000         6              False             False   
10    83000          40000         7              False             False   
11    79000          21000         7              False             False   
12    59000          33000         5              False             False   

    Car Model_Mercedez Benz C class  
0                             False  
1                             False  
2                             False  
3                             False  
4                             False  
5                             False  
6                             False  
7                             False  
8                             False  
9                              True  
10                             True  
11                             True  
12                             True

**2. How to import `NumPy` library?** 

In [5]:
# To avoid overwriting the output, please code here 
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [5]:
list_1 = [1,2,3,4,5]

In [13]:
# To avoid overwriting the output, please code here
array_1 = np.array(list_1)
array_1

array([1, 2, 3, 4, 5])

In [15]:
array_1.dtype

dtype('int32')

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [21]:
# To avoid overwriting the output, please code here 
array = np.arange(6)
array

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [36]:
# To avoid overwriting the output, please code here
zeros_array = np.zeros(5)

In [38]:
zeros_array

array([0., 0., 0., 0., 0.])

**6. Generate the following `matrix`.**

In [45]:
# To avoid overwriting the output, please code here 
matrix = np.zeros((3, 4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [47]:
# To avoid overwriting the output, please code here 
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [53]:
# To avoid overwriting the output, please code here 
tens_array = np.full(5, 10.)
tens_array

array([10., 10., 10., 10., 10.])

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [63]:
# To avoid overwriting the output, please code here 
even_numbers = np.arange(52, 100, 2)
even_numbers

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [67]:
# To avoid overwriting the output, please code here 
array_2 = np.linspace(0, 1, 10, retstep=True)
array_2

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [69]:
# To avoid overwriting the output, please code here 
vector_1 = np.arange(25)
vector_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
# To avoid overwriting the output, please code here 
matrix = vector_1.reshape(5, 5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [81]:
# To avoid overwriting the output, please code here 
# We cannot use shape directly to reshape an array
vector_1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

In [87]:
# To avoid overwriting the output, please code here 
matrix_1 = np.linspace(0.1, 2.5, num=25).reshape(5,5)
matrix_1

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [91]:
# To avoid overwriting the output, please code here 
array_3 = np.linspace(0, 24, 25, dtype=int).reshape(5,5)
array_3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [31]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

**15. How to generate a single random integer number using NumPy built-in function?**

In [7]:
# To avoid overwriting the output, please code here 
random_int = np.random.randint(10)
random_int

6

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [9]:
# To avoid overwriting the output, please code here 
random_matrix = np.random.rand(7, 5)
random_matrix

array([[0.41456263, 0.86338238, 0.43133645, 0.19439462, 0.25484753],
       [0.48650492, 0.87288013, 0.35105553, 0.0836207 , 0.80484351],
       [0.14042961, 0.14879403, 0.0177605 , 0.28711518, 0.64135358],
       [0.91850534, 0.60441803, 0.25113238, 0.39490014, 0.63017212],
       [0.29992225, 0.25680705, 0.42467218, 0.3961926 , 0.95174718],
       [0.88467611, 0.69463261, 0.0972889 , 0.50162838, 0.24206964],
       [0.37518911, 0.90282468, 0.18394088, 0.2580939 , 0.46128423]])

[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [11]:
# To avoid overwriting the output, please code here 
identity_matrix = np.eye(5)
matrix_4 = 5 * identity_matrix
matrix_4

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 