# NumPy Essentials (Part:1 - Arrays)

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 1.<br>

As a fundamental package for scientific computing, NumPy provides the foundations of mathematical, scientific, engineering and data science programming within the Python Echo-system. NumPy’s main object is the homogeneous multidimensional array.<br> 

**NumPY stands for? Ans: Numerical Python  
Numpy developed by? Ans: Travis Oliphant**

**I hope that you have already installed NumPy, let's move on a create a new notebook to explore more about NumPy.** <br>

# Numpy Arrays
### `arange()`,  `linspace()`, `zeros()`,  `ones()`, `eye()`, `rand()`, `randn()`, `randint()`
### Methods: `reshape()`, `max()`, `min()`, `argmax()`, `argmin()`<br>
### Attributes: `size, shape, dtype` 
### Indexing & slicing of 1-D arrays (vectors)
###  Indexing & slicing 2-D arrays (matrices)

In [1]:
# Let import NumPy
import numpy as np

NumPy has many built-in functions and capabilities. We will focus on some of the most important and key concepts of this powerful library.

# Numpy Arrays

NumPy arrays will be the main concept that we will be using in this course. These arrays essentially come in two flavors: <br>
* **Vectors:** Vectors are strictly 1-dimensional array
*  **Matrices:** Matrices are 2-dimensional (matrix can still have only one row or one column).

## Creating NumPy Arrays

### From Python data type (e.g. List, Tuple)

In [6]:
# Lets create a Python list. 
my_list = [-1,0,1] 

my_list

[-1, 0, 1]

To create a NumPy array, from a Python data structure, we use NumPy's array function. <br>
The NumPy's array function can be accessed by typing "np.array". <br>
We need to cast our Python data structure, my_list, as a parameter to the array function.<br>

In [9]:
my_array = np.array(my_list)

my_array

array([-1,  0,  1])

In [11]:
# Lets create and cast a list of list to generate 2-D array 
my_matrix = [[1,2,3],[4,5,6]]
my_matrix

[[1, 2, 3], [4, 5, 6]]

In [13]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
matrix_one.shape

(2, 3)

In [17]:
# We can use Tuple instead of list as well. 
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array

array([-1,  0,  1])

### Array creation using NumPy's Built-in methods

Most of the times, we use NumPy built-in methods to create arrays. These are much simpler and faster.

### `arange()`

* arange() is very much similar to Python function range() <br>
* Syntax: arange([start,] stop[, step,], dtype=None) <br>
* Return evenly spaced values within a given interval. <br>

*Press shift+tab for the documentation.*

In [21]:
num = np.arange(100) # similar to range() in Python, not including 100  
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
# We can give the step
np.arange(3,10,2)

array([3, 5, 7, 9])

In [25]:
# We can give the step and dtype
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

### `linspace()`
Return evenly spaced numbers over a specified interval.<br>
*Press shift+tab for the documentation.*

In [28]:
# start from 1 & end at 15 with 15 evenly spaced points b/w 1 to 15.
np.linspace(1, 20, 100, retstep=True)

(array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
         1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
         2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
         3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
         4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
         5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
         6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
         7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
         8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
         9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
        10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
        11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
        12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
        13.47474747, 13.66666667, 13.85858586, 14.0

In [30]:
my_linspace = np.linspace(9, 15, 20, retstep=True)
my_linspace

(array([ 9.        ,  9.31578947,  9.63157895,  9.94736842, 10.26315789,
        10.57894737, 10.89473684, 11.21052632, 11.52631579, 11.84210526,
        12.15789474, 12.47368421, 12.78947368, 13.10526316, 13.42105263,
        13.73684211, 14.05263158, 14.36842105, 14.68421053, 15.        ]),
 0.3157894736842105)

In [32]:
np.linspace(1,2,30) # 1-D array 

array([1.        , 1.03448276, 1.06896552, 1.10344828, 1.13793103,
       1.17241379, 1.20689655, 1.24137931, 1.27586207, 1.31034483,
       1.34482759, 1.37931034, 1.4137931 , 1.44827586, 1.48275862,
       1.51724138, 1.55172414, 1.5862069 , 1.62068966, 1.65517241,
       1.68965517, 1.72413793, 1.75862069, 1.79310345, 1.82758621,
       1.86206897, 1.89655172, 1.93103448, 1.96551724, 2.        ])

## Don't Confuse!
  * <b>arange() takes 3rd argument as step size.<b><br>
  * <b>linspace() take 3rd argument as no of point we want.<b>

In [35]:
x = np.arange(0, 16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
x.shape

(16,)

In [39]:
x.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
y = x.reshape(2, 2, 4)
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [43]:
y.shape

(2, 2, 4)

In [47]:
x = y.reshape(16,)

In [49]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
x.shape

(16,)

## Random 

We can also create arrays with random numbers using Numpy's built-in functions in Random module.<br>
*np.random. and then press tab for the options with random*

### `rand()`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [55]:
np.random.rand(4) # 1-D array with three elements

array([0.0314741 , 0.17602844, 0.73429669, 0.82829088])

In [61]:
np.random.rand(6,4)  # row, col, note we are not passing a tuple here, each dimension as a separate argument

array([[0.81802606, 0.07029776, 0.77745804, 0.95071687],
       [0.97629952, 0.67919538, 0.94841597, 0.78139674],
       [0.29602062, 0.79979873, 0.13723781, 0.2310986 ],
       [0.33689838, 0.12047029, 0.6466233 , 0.27616418],
       [0.09978946, 0.76545895, 0.6817442 , 0.86502944],
       [0.31894537, 0.61230142, 0.06310935, 0.06862576]])

### `randn()`

Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform.<br>
*Press shift+tab for the documentation.*

In [64]:
np.random.randn(20, 5)

array([[-0.63401173,  0.44933995,  0.18168633,  0.74461314, -1.26971187],
       [ 0.85223448, -2.10310161,  1.33277447,  0.10260254,  0.70281375],
       [ 0.33348294, -0.27822116, -1.18375408,  1.00358563,  0.49113421],
       [-0.43863054, -0.4221978 ,  3.00246752,  0.30908188, -1.20201366],
       [ 0.18922865,  0.75589392,  0.29006906, -0.12892852,  0.07580674],
       [-1.46602639, -0.99489161, -0.16924598, -0.04736364,  0.90857396],
       [-0.53724815, -0.03168452,  1.35561696, -0.55164459,  0.02475872],
       [ 2.06742202,  0.03586453,  0.7851166 ,  0.16359219,  0.1360958 ],
       [-0.0120611 ,  0.41831709, -0.6545613 , -0.09585352,  1.55168254],
       [ 0.81249351,  1.0421733 , -0.08822099, -1.74485704, -1.18320833],
       [ 2.04497632,  1.21547621,  0.33422342,  0.82953532,  0.30974055],
       [-0.64059187, -1.76406578,  0.04672514, -0.61520106,  0.82531179],
       [-0.72050793,  0.36899791, -1.94148011,  1.81108446, -0.95365129],
       [-0.62122109,  0.11966549, -0.2

In [66]:
normal_array = np.random.randn(1000,1) # no tuple, each dimension as a separate argument
normal_array

array([[ 4.54693054e-01],
       [ 8.47684031e-01],
       [-8.34440124e-01],
       [-9.13081332e-01],
       [ 1.62415734e+00],
       [-5.09529339e-01],
       [ 4.70005377e-01],
       [-3.45317861e-01],
       [-4.15555002e-01],
       [-6.31666186e-02],
       [-2.35801154e-01],
       [ 1.75001860e-01],
       [-5.65326973e-01],
       [ 1.05959509e+00],
       [-7.30562705e-01],
       [-9.71894109e-01],
       [ 1.75832363e-01],
       [ 1.29363854e+00],
       [ 4.30723825e-01],
       [-3.52008542e+00],
       [ 2.80247449e-01],
       [ 5.24505126e-01],
       [-1.07171773e+00],
       [-4.81996927e-01],
       [ 2.47470832e-01],
       [-1.18557688e+00],
       [-1.56918335e+00],
       [-8.00859432e-01],
       [ 9.44627183e-02],
       [ 1.01046125e+00],
       [ 1.58479566e+00],
       [ 1.32615429e+00],
       [-1.09742872e+00],
       [ 1.90509225e-01],
       [ 1.14982403e+00],
       [ 8.07023916e-01],
       [-8.20491736e-01],
       [ 3.81527711e-01],
       [ 7.0

In [ ]:
import pandas as pd

df = pd.DataFrame(data=normal_array, columns=['A'])
df

In [ ]:
df['A'].hist(bins=30)

### `randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

In [72]:
np.random.randint(1, 200, 5) #returns one random int, 1 inclusive, 100 exclusive

array([111, 120,  71,  95,  22])

In [78]:
np.random.randint(100,200,20).reshape(4,5) #returns ten random int,

array([[156, 193, 181, 193, 163],
       [150, 138, 157, 154, 111],
       [183, 145, 199, 199, 115],
       [108, 124, 170, 138, 152]])

In [80]:
arr0 = np.random.randint(low=1000, high=2000, size=[5,8])
arr0

array([[1081, 1579, 1304, 1596, 1509, 1513, 1227, 1256],
       [1519, 1199, 1936, 1195, 1568, 1179, 1974, 1812],
       [1298, 1240, 1219, 1540, 1263, 1994, 1772, 1414],
       [1042, 1094, 1845, 1549, 1227, 1555, 1294, 1608],
       [1821, 1723, 1443, 1490, 1232, 1381, 1808, 1709]])

## Array Methods & Attributes
Some important Methods and Attributes are important to know:<br>

### Methods:
* reshape(), max(), min(), argmax(), argmin()<br>

In [91]:
# lets create 2 arrays using arange() and randint()
array_ranint = np.random.randint(0,100,10)

In [93]:
array_ranint

array([43, 42, 12, 78, 43, 76, 90, 48, 44, 14])

#### `max()` & `min()`
Useful methods for finding max or min values.

In [96]:
array_ranint.min()

12

In [98]:
array_ranint.max()

90

#### `argmax()` & `argmin()`
To find the index locations of max and min values in array

In [101]:
array_ranint.argmax() # index starts from 0

6

In [103]:
array_ranint.argmin()

2

### Attributes
* `size, shape, dtype` 

In [105]:
array_arange=np.arange(16)

In [107]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [109]:
array_arange.shape

(16,)

In [111]:
array_arange.size

16

In [113]:
# Size of the array 
array_arange.itemsize

4

In [115]:
# Type of the data.
array_arange.dtype

dtype('int32')

In [117]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [119]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [121]:
array_arange.shape = (4,4)

In [123]:
array_arange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
array_arange.reshape(1,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [131]:
array_arange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [133]:
array_arange.reshape(1,16).shape

(1, 16)

### Indexing & slicing of 1-D arrays (vectors)

In [135]:
array_1d = np.array([-10, -2, 0, 2, 17, 106,200])

In [137]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [139]:
array_1d[2]

0

In [141]:
# Getting a range value
array_1d[0:3]

array([-10,  -2,   0])

In [143]:
# Using -ve index 
array_1d[-2]

106

In [145]:
# Using -ve index for a range 
array_1d[1:-2]

array([-2,  0,  2, 17])

In [147]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [149]:
array_1d[:2]

array([-10,  -2])

In [151]:
array_1d[2:]

array([  0,   2,  17, 106, 200])

In [153]:
# Assigning a new value to a certain index in the array 
array_1d[0] = -102

In [155]:
array_1d
# The first element is changed to -102

array([-102,   -2,    0,    2,   17,  106,  200])

###  Indexing & slicing 2-D arrays (matrices)

Lets create an array with 24 elements using arange() and convert it to 2D matrix using "shape".<br>
*note, 6 x 4 = 24*

In [158]:
array_2d = np.arange(24)
array_2d = array_2d.reshape(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

To access any element, the general format is: <br>
* **`array_2d[row][col]`** <br>or<br> 
* **`array_2d[row,col]`**. 

We will use `[row,col]`, easier to use comma ',' for clarity.

In [161]:
# To get a complete row
array_2d[2]

array([ 8,  9, 10, 11])

In [163]:
array_2d[-4] # -0 and 0 is same inedex

array([ 8,  9, 10, 11])

In [165]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [167]:
# another way 
row = 5
column = 2
array_2d[row, column]

22

In [169]:
# Just to make sure, using [row][col] :)
array_2d[5][2]

22

In [171]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [173]:
# 2D array slicing
array_2d[:2,:2] 

array([[0, 1],
       [4, 5]])

### Broadcasting

Numpy arrays are different from normal Python lists because of their ability to broadcast. We will only cover the basics, for further details on broadcasting rules, click [here](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) <br>
Another good read on [broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)!<br>

**Lets start with some simple examples:**

In [175]:
# Lets create an array using arange()
array_1d = np.arange(0,10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Take a slice of the array and set it equal to some number, say 500.<br>

        array_1d[0:5] = 500 
this will **broadcast the value of 500 to the first 5 elements** of the array_1d

In [178]:
array_1d[0:5] = 500 
array_1d

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [186]:
# Lets create a 2D martix with ones
array_2d = np.ones((4,4), dtype=int)
array_2d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [188]:
# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
array_2d

array([[300, 300, 300, 300],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1]])

In [190]:
# Lets create a simple 1-D array and broadcast to array_2d
array_2d + np.arange(0,4)  #[0,1,2,3]
# try array_2d + np.arange(0,3), did this work? if not why?

array([[300, 301, 302, 303],
       [  1,   2,   3,   4],
       [  1,   2,   3,   4],
       [  1,   2,   3,   4]])

In [192]:
array_2d

array([[300, 300, 300, 300],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1]])

In [194]:
array_2d * np.arange(0,4)

array([[  0, 300, 600, 900],
       [  0,   1,   2,   3],
       [  0,   1,   2,   3],
       [  0,   1,   2,   3]])

In [196]:
array_2d + 300
# array_2d + [300,2], did it work? if not why?

array([[600, 600, 600, 600],
       [301, 301, 301, 301],
       [301, 301, 301, 301],
       [301, 301, 301, 301]])

In [198]:
array_2d

array([[300, 300, 300, 300],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1]])

In [200]:
array_2d[[3, 1]]

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [202]:
array_2d[:,[2]]

array([[300],
       [  1],
       [  1],
       [  1]])

In [ ]:
array_2d

In [ ]:
# We can use any order
array_2d[[3, 1]]

In [ ]:
# lets try another matrix
array_2d = np.arange(24)
array_2d.shape = (6,4)
array_2d

In [ ]:
# grabbing rows
array_2d[[2,3]] #[2][3]

In [ ]:
array_2d[:3, [2,3]]

In [ ]:
# grabbing columns
#array_2d[:,3:2]
array_2d[:,[3,2]]

In [ ]:
# Lets create a simple array using arange()
array_1d = np.arange(1,11)
array_1d

We can apply condition such as >, <, == etc

In [ ]:
array_1d > 3

In [ ]:
# lets create a bool_array for some condition, say array_1d > 3
bool_array = array_1d > 3
bool_array

Lets create a mask to **filter out the even numbers in "array_1d"**

In [ ]:
array_1d % 2

In [ ]:
0 == array_1d % 2

In [ ]:
# A number is even if, number % 2 is "0"
mod_2_mask_1d = array_1d % 2 != 0 
mod_2_mask_1d

In [ ]:
array_1d

In [ ]:
array_1d[mod_2_mask_1d] #array_1d[[False,  True, False,  True, False,  True, False,  True, False,True]]

## NumPy Operations 

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 2.<br>

Let's talk about NumPy operations in this section, such as:

* <b>Arithmetic operations</b>
* <b>Universal Functions (ufunc)</b>
 

## Arithmetic operations

We can perform arithmetic operations with NumPy arrays. <br>
Let's learn with examples:

In [ ]:
# Let's create an array using arange() method
arr = np.arange(0,5)
arr  

In [ ]:
# Adding two arrays
arr + arr  #[0, 1, 2, 3, 4] + [0, 1, 2, 3, 4]

In [ ]:
# Subtracting two arrays
arr - arr

In [ ]:
# Multiplication
arr * arr

In [ ]:
# Division
arr / arr
# warning and 0/0 is replaced with nan

In [ ]:
1/arr #[0, 1, 2, 3, 4]
# warning for 1/0, inf

In [ ]:
# Power of all the elements in an array
arr ** 2

In [ ]:
# Multiplication with scalar 
2 * arr #[0, 1, 2, 3, 4]

## Universal functions

NumPy have a range of built-in [universal functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html) (ufunc). These are essentially just mathematical operations and we can use them to perform specific task, associate with the function, across the NumPy array.<br>
Let's learn with examples:

In [ ]:
# Square root
np.sqrt(arr) #[0, 1, 2, 3, 4]

In [ ]:
# max and min values
np.max(arr), np.min(arr)

In [ ]:
arr.max()

In [ ]:
# Trigonometric functions, e.g. sin, cos, tan, arcsin, ......
np.sin(arr)

**Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [ ]:
#18a:
# To avoid overwriting the output, please code here 

In [ ]:
array_2d= np.arange(30).reshape(6,5)
array_2d

**Calculate the sum of all the numbers in array_2d?**

In [ ]:
array_2d.sum()

In [ ]:
array_2d.sum(axis=1)

**Calculate sum of all the rows and columns in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [ ]:
print("Row sum:", array_2d.sum(axis=1))
print("Columns sum:", array_2d.sum(axis=0))

**Calculate the standard deviation of the values in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [ ]:
array_2d.std()

**Create a boolean mask and list out the numbers that are not divisible by 3 in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [ ]:
array_2d

In [ ]:
array_2d % 3 == 0

In [ ]:
mask_mod_3 = 0 != array_2d % 3
mask_mod_3

In [ ]:
mask_mod_3 = 0 != array_2d % 3  # Creating mask for the said condition
array_2d[mask_mod_3]            # pass the boolean mask to array_2d to return the required results

In [ ]:
np.zeros(5)